#!/bin/sh

prefix=''

which oa 2>&1 > /dev/null && prefix='oa'

if [ $# = 1 ]
then
  fn="$1"

  dir=`dirname "$fn"`
  fp="$dir/`basename $fn`"

  num=`ls "$dir"/*.* | grep -n -F "$fp" | cut -d : -f 1`

  $prefix sxiv -s -n "$num" "$dir"/*.*
else
  $prefix sxiv -s "$@"
fi
